Repository openpmix/openpmix, pull requests merged in 2018-08, with the labels that each got.

#808 Implement job control and sensor APIs
  .gitignore
  include/pmix_common.h.in
  src/common/pmix_control.c
  src/mca/psensor/base/psensor_base_stubs.c
  src/mca/psensor/heartbeat/psensor_heartbeat.c
  src/mca/psensor/heartbeat/psensor_heartbeat.h
  src/mca/psensor/heartbeat/psensor_heartbeat_component.c
  src/server/pmix_server.c
  src/server/pmix_server_ops.c
  test/simple/Makefile.am
  test/simple/simpjctrl.c
  test/simple/simptest.c
Labels: Target: 3.x

#810 Missed one spot where we need to avoid the cbfunc
  src/server/pmix_server_ops.c
Labels: Target: 3.x

#812 Silence Coverity warning
  src/common/pmix_control.c
Labels: Target: 3.x

#809 Implement job control and sensor APIs
  .gitignore
  include/pmix_common.h.in
  src/common/pmix_control.c
  src/mca/psensor/base/psensor_base_stubs.c
  src/mca/psensor/heartbeat/psensor_heartbeat.c
  src/mca/psensor/heartbeat/psensor_heartbeat.h
  src/mca/psensor/heartbeat/psensor_heartbeat_component.c
  src/server/pmix_server.c
  src/server/pmix_server_ops.c
  test/simple/Makefile.am
  test/simple/simpjctrl.c
  test/simple/simptest.c
Labels: bug

#818 configury: define C11 macros once
  config/pmix_setup_cc.m4
Labels: Target: 2.x, bug

#805 dstore: ds21 locks are aligned to the size of the cache line
  config/pmix.m4
  src/mca/common/dstore/dstore_segment.c
  src/mca/common/dstore/dstore_segment.h
  src/mca/gds/ds21/gds_ds21_lock_pthread.c
Labels: enhancement

#820 Update sensor support
  src/mca/psensor/file/psensor_file.c
  src/mca/psensor/heartbeat/psensor_heartbeat.c
  src/mca/ptl/base/ptl_base_sendrecv.c
  src/server/pmix_server.c
Labels: Target: 2.x, Target: 3.x

#825 util/path: only include sys/mount.h once
  src/util/path.c
Labels: code-cleanup

#822 Implement job control and sensor APIs in v2 of standard
  .gitignore
  include/pmix_common.h.in
  src/common/pmix_control.c
  src/mca/psensor/base/psensor_base_stubs.c
  src/mca/psensor/file/psensor_file.c
  src/mca/psensor/heartbeat/psensor_heartbeat.c
  src/mca/psensor/heartbeat/psensor_heartbeat.h
  src/mca/psensor/heartbeat/psensor_heartbeat_component.c
  src/mca/ptl/base/ptl_base_sendrecv.c
  src/server/pmix_server.c
  src/server/pmix_server_ops.c
  test/simple/Makefile.am
  test/simple/simpjctrl.c
  test/simple/simptest.c
Labels: Target: 2.x, bug
