Repository openpmix/openpmix, pull requests merged in 2018-11, with the labels that each got.

#918 passing a bool to va_start() is undefined
  src/util/os_path.c
  src/util/os_path.h
  src/util/show_help.c
  src/util/show_help.h
Labels: Target: 2.x, Target: 3.x, Target: 4.x, code-cleanup

#910 Dstore: fix key publishing logic
  src/mca/common/dstore/dstore_base.c
Labels: Target: 2.x, Target: 3.x, Target: 4.x, enhancement

#917 v3.1/dstore: ds21 locks are aligned to the size of the cache line
  config/pmix.m4
  src/mca/common/dstore/dstore_segment.c
  src/mca/common/dstore/dstore_segment.h
  src/mca/gds/ds21/gds_ds21_lock_pthread.c
Labels: enhancement

#916 v2.2/dstore: ds21 locks are aligned to the size of the cache line
  config/pmix.m4
  src/mca/common/dstore/dstore_segment.c
  src/mca/common/dstore/dstore_segment.h
  src/mca/gds/ds21/gds_ds21_lock_pthread.c
Labels: enhancement

#911 Dstor/v2.2/fmt optimizations
  src/mca/common/dstore/Makefile.am
  src/mca/common/dstore/dstore_base.c
  src/mca/common/dstore/dstore_base.h
  src/mca/common/dstore/dstore_common.h
  src/mca/common/dstore/dstore_file.h
  src/mca/gds/ds12/Makefile.am
  src/mca/gds/ds12/gds_ds12_base.c
  src/mca/gds/ds12/gds_ds12_file.c
  src/mca/gds/ds12/gds_ds12_file.h
  src/mca/gds/ds12/gds_ds20_file.c
  src/mca/gds/ds21/Makefile.am
  src/mca/gds/ds21/gds_ds21_base.c
  src/mca/gds/ds21/gds_ds21_file.c
  src/mca/gds/ds21/gds_ds21_file.h
Labels: enhancement

#912 Dstor/v3.1/fmt optimizations
  src/mca/common/dstore/Makefile.am
  src/mca/common/dstore/dstore_base.c
  src/mca/common/dstore/dstore_base.h
  src/mca/common/dstore/dstore_common.h
  src/mca/common/dstore/dstore_file.h
  src/mca/gds/ds12/Makefile.am
  src/mca/gds/ds12/gds_ds12_base.c
  src/mca/gds/ds12/gds_ds12_file.c
  src/mca/gds/ds12/gds_ds12_file.h
  src/mca/gds/ds12/gds_ds20_file.c
  src/mca/gds/ds21/Makefile.am
  src/mca/gds/ds21/gds_ds21_base.c
  src/mca/gds/ds21/gds_ds21_file.c
  src/mca/gds/ds21/gds_ds21_file.h
Labels: enhancement

#934 Ensure SIGCHLD is unblocked in simptest
  test/simple/simptest.c
Labels: Target: 2.x, Target: 3.x, Target: 4.x

#938 Default the v2.0 GDS to "ds12,hash"
  src/mca/ptl/tcp/ptl_tcp_component.c
Labels: Target: 2.x, Target: 3.x, bug

#955 autogen.sh: remove outdated sym link
  autogen.sh
Labels: code-cleanup

#958 Remove all references to autogen.sh
  HACKING
  INSTALL
  contrib/make_dist_tarball
  contrib/nightly/create_tarball.sh
  contrib/pmix_jenkins.sh
Labels: bug

#956 Fix race conditions in tracked requests
  src/include/pmix_globals.h
  src/mca/ptl/base/ptl_base_sendrecv.c
  src/server/pmix_server.c
  src/server/pmix_server_get.c
  src/server/pmix_server_ops.c
  test/simple/simpdmodex.c
Labels: Target: 2.x, Target: 3.x, Target: 4.x, bug
