Repository openpmix/openpmix, pull requests merged in 2018-10, with the labels that each got.

#856 Further cleanup use of strncpy
  include/pmix_common.h.in
  src/client/pmix_client.c
  src/include/pmix_config_bottom.h
  src/mca/pshmem/base/pshmem_base_frame.c
  test/utils.c
Labels: Target: 2.x, Target: 3.x, Target: 4.x

#858 Further cleanup use of strncpy
  include/pmix_common.h.in
  include/pmix_extend.h
  src/client/pmi1.c
  src/client/pmi2.c
  src/client/pmix_client.c
  src/client/pmix_client_fence.c
  src/client/pmix_client_get.c
  src/client/pmix_client_pub.c
  src/client/pmix_client_spawn.c
  src/common/pmix_data.c
  src/common/pmix_iof.h
  src/event/pmix_event.h
  src/event/pmix_event_notification.c
  src/event/pmix_event_registration.c
  src/include/pmix_config_bottom.h
  src/mca/base/pmix_mca_base_component_repository.c
  src/mca/bfrops/base/bfrop_base_copy.c
  src/mca/bfrops/base/bfrop_base_unpack.c
  src/mca/bfrops/v12/copy.c
  src/mca/bfrops/v12/unpack.c
  src/mca/bfrops/v20/copy.c
  src/mca/bfrops/v20/unpack.c
  src/mca/gds/ds12/gds_dstore.c
  src/mca/pif/bsdx_ipv4/pif_bsdx.c
  src/mca/pif/bsdx_ipv6/pif_bsdx_ipv6.c
  src/mca/pif/linux_ipv6/pif_linux_ipv6.c
  src/mca/pif/posix_ipv4/pif_posix.c
  src/mca/pif/solaris_ipv6/pif_solaris_ipv6.c
  src/mca/pnet/tcp/pnet_tcp.c
  src/mca/pnet/test/pnet_test.c
  src/mca/preg/native/preg_native.c
  src/mca/psensor/file/psensor_file.c
  src/mca/psensor/heartbeat/psensor_heartbeat.c
  src/mca/pshmem/mmap/pshmem_mmap.c
  src/mca/ptl/tcp/ptl_tcp.c
  src/mca/ptl/tcp/ptl_tcp_component.c
  src/mca/ptl/usock/ptl_usock_component.c
  src/server/pmix_server.c
  src/server/pmix_server_get.c
  src/server/pmix_server_ops.c
  src/tool/pmix_tool.c
  src/tools/plookup/plookup.c
  src/util/argv.c
  src/util/basename.c
  src/util/hash.c
  src/util/keyval_parse.c
  src/util/output.c
  src/util/pif.c
  test/utils.c
Labels: bug, code-cleanup

#870 Update simptest to return client status
  test/simple/simptest.c
Labels: Target: 3.x

#871 Update simptest to return client status
  test/simple/simptest.c
Labels: Target: 3.x

#872 Update simptest to return client status
  test/simple/simptest.c
Labels: Target: 2.x

#873 Update simptest to return client status
  test/simple/simptest.c
Labels: Target: 2.x

#874 Update simptest to return client status
  test/simple/simptest.c
Labels: Target: 2.x

#878 Backport fix from OMPI - correct typo
  src/mca/pinstalldirs/config/Makefile.am
Labels: Target: 2.x, Target: 3.x, Target: 4.x, bug

#826 Implement PMIx group collective APIs
  .gitignore
  bindings/python/construct.py
  examples/Makefile.am
  examples/asyncgroup.c
  examples/group.c
  include/pmix.h
  include/pmix_common.h.in
  include/pmix_extend.h
  src/client/Makefile.include
  src/client/pmix_client_group.c
  src/common/pmix_strings.c
  src/event/pmix_event_notification.c
  src/include/pmix_globals.h
  src/mca/bfrops/base/base.h
  src/mca/bfrops/base/bfrop_base_fns.c
  src/mca/bfrops/bfrops.h
  src/mca/bfrops/v12/copy.c
  src/mca/bfrops/v12/internal.h
  src/mca/bfrops/v20/copy.c
  src/mca/bfrops/v20/internal.h
  src/mca/ptl/base/ptl_base_sendrecv.c
  src/server/pmix_server.c
  src/server/pmix_server_ops.c
  src/server/pmix_server_ops.h
  src/tool/pmix_tool.c
  src/util/error.c
  test/simple/simptest.c
Labels: RFC, Target: 4.x

#879 Backport fix from OMPI - correct typo
  src/mca/pinstalldirs/config/Makefile.am
Labels: bug

#880 Cherry-picks from master
  config/pmix_setup_hwloc.m4
  src/mca/pinstalldirs/config/Makefile.am
Labels: bug

#881 Cherry-picks from master
  config/pmix_setup_hwloc.m4
  src/mca/pinstalldirs/config/Makefile.am
Labels: bug

#886 Pickup a couple of bug fix commits
  src/hwloc/hwloc.c
  src/mca/pshmem/base/pshmem_base_frame.c
  src/server/pmix_server.c
Labels: bug

#887 Ensure we only open the pshmem framework once
  config/pmix_mca.m4
  src/mca/pshmem/base/pshmem_base_frame.c
Labels: bug

#888 Fix typo in configure logic
  config/pmix_mca.m4
Labels: bug

#895 Enable PMIx_Group_construct to return a context ID
  examples/group.c
  include/pmix_common.h.in
  include/pmix_server.h
  src/client/pmix_client_group.c
  src/server/pmix_server_ops.c
Labels: Target: 4.x

#875 ptl/usock: Guard against assumption that zero-length credential is NULL
  src/mca/ptl/usock/ptl_usock_component.c
Labels: bug

#897 Pull gds locking of modex up to improve performance.
  src/mca/common/dstore/dstore_base.c
  src/mca/common/dstore/dstore_common.h
  src/mca/gds/base/base.h
  src/mca/gds/base/gds_base_fns.c
  src/mca/gds/ds12/gds_ds12_base.c
  src/mca/gds/ds21/gds_ds21_base.c
  src/mca/gds/gds.h
  src/mca/gds/hash/gds_hash.c
  src/server/pmix_server.c
Labels: enhancement

#902 Wrap the inner dstore kv in an object.
  src/mca/common/dstore/dstore_base.c
Labels: bug

#904 Wrap the inner dstore kv in an object.
  src/mca/common/dstore/dstore_base.c
Labels: bug

#903 Wrap the inner dstore kv in an object.
  src/mca/common/dstore/dstore_base.c
Labels: bug
