Repository openpmix/openpmix, pull requests merged in 2018-03, with the labels that each got.

#685 Correct an extern statement
  test/server_callbacks.c
Labels: bug

#684 Correct an extern statement
  test/server_callbacks.c
Labels: bug

#686 Add a `PMIX_VERSION_RELEASE` to the pmix_version.h
  config/pmix.m4
  include/pmix_version.h.in
Labels: enhancement

#687 Add a `PMIX_VERSION_RELEASE` to the pmix_version.h
  config/pmix.m4
  include/pmix_version.h.in
Labels: enhancement

#688 Add a `PMIX_VERSION_RELEASE` to the pmix_version.h
  config/pmix.m4
  include/pmix_version.h.in
Labels: enhancement

#450 OpenMP/MPI Coordination
  include/pmix_common.h.in
Labels: RFC, Target: 3.x

#691 Provide spawned keys to resulting procs
  src/server/pmix_server.c
  src/server/pmix_server_ops.c
  test/simple/simptest.c
Labels: Target: 2.x, bug

#697 Fixed the direct modex request
  src/server/pmix_server_get.c
Labels: Target: 2.x, Target: 3.x, bug

#698 Fixed the direct modex request
  src/server/pmix_server_get.c
Labels: bug
