Repository openpmix/openpmix, pull requests merged in 2018-12, with the labels that each got.

#967 v3.1/dstor: fix detection of invalidated key
  src/mca/common/dstore/dstore_file.h
  src/mca/gds/ds12/gds_ds12_file.c
  src/mca/gds/ds12/gds_ds20_file.c
  src/mca/gds/ds21/gds_ds21_file.c
Labels: bug

#976 Correct typo on proc assignment
  src/common/pmix_query.c
Labels: Target: 3.x

#978 Silence unnecessary warning message
  src/mca/ptl/tcp/ptl_tcp_component.c
Labels: Target: 3.x

#980 iof: plug a memory leak in the pmix_iof_req_t destructor
  src/include/pmix_globals.c
Labels: Target: 3.x, enhancement

#985 plug a memory leak in pmix_value_destruct()
  include/pmix_common.h.in
Labels: code-cleanup

#986 plug a memory leak in the spcbfunc() callback
  src/server/pmix_server_ops.c
Labels: bug

#987 Plug misc memory leaks
  src/event/pmix_event_notification.c
  src/include/pmix_globals.c
  src/mca/pnet/tcp/pnet_tcp.c
  src/server/pmix_server_ops.c
Labels: enhancement

#988 pnet/base: plug misc memory leaks
  src/mca/pnet/base/pnet_base_fns.c
Labels: enhancement

#993 Restore prior sizes for max nslen and keylen
  include/pmix_common.h.in
Labels: Target: 2.x, Target: 3.x, code-cleanup

#992 Plug misc memory leaks
  include/pmix_common.h.in
  src/server/pmix_server.c
  src/server/pmix_server_ops.c
  src/server/pmix_server_ops.h
Labels: enhancement

#968 v2.2/dstor: fix detection of invalidated key
  src/mca/common/dstore/dstore_file.h
  src/mca/gds/ds12/gds_ds12_file.c
  src/mca/gds/ds12/gds_ds20_file.c
  src/mca/gds/ds21/gds_ds21_file.c
Labels: bug

#963 Use fastpath to get keys without thread shifting, if supported by GDS
  include/pmix_common.h.in
  src/client/pmix_client_get.c
  src/mca/common/dstore/dstore_base.c
  src/mca/common/dstore/dstore_base.h
  src/mca/gds/ds12/gds_ds12_base.c
  src/mca/gds/ds21/gds_ds21_base.c
  src/mca/gds/gds.h
  src/mca/gds/hash/gds_hash.c
  src/runtime/pmix_params.c
Labels: IN PROGRESS, WIP-DNM, enhancement

#999 server: have query_cbfunc invoke the release callback when available
  src/server/pmix_server.c
Labels: enhancement

#996 gds/ds12: plug a memory leak in pmix_ds12_lock_finalize()
  src/mca/gds/ds12/gds_ds12_lock_pthread.c
Labels: enhancement

#998 dstore/base: plug a memory leak in pmix_common_dstor_del_nspace()
  src/mca/common/dstore/dstore_base.c
Labels: enhancement

#991 Attempt to address the case where data isn't found
  src/server/pmix_server_get.c
Labels: Target: 2.x, Target: 3.x, bug

#1009 gds/base: plug a memory leak in pmix_gds_base_store_modex()
  src/mca/gds/base/gds_base_fns.c
Labels: enhancement

#1011 Coverity fixes for test suite
  test/server_callbacks.c
  test/test_server.c
Labels: bug
