Repository openpmix/openpmix, pull requests merged in 2018-09, with the labels that each got.

#827 common/pmix_strings: silence warnings
  src/common/pmix_strings.c
Labels: code-cleanup

#828 Fix event notification operations
  include/pmix_common.h.in
  include/pmix_extend.h
  src/client/pmix_client.c
  src/event/pmix_event.h
  src/event/pmix_event_notification.c
  src/server/pmix_server_ops.c
  src/tool/pmix_tool.c
  src/util/error.c
  test/simple/simptest.c
Labels: Target: 2.x, Target: 3.x, Target: 4.x, bug

#830 Fix event notification operations
  include/pmix_common.h.in
  src/client/pmix_client.c
  src/event/pmix_event.h
  src/event/pmix_event_notification.c
  src/server/pmix_server_ops.c
  src/tool/pmix_tool.c
  test/simple/simptest.c
Labels: bug

#829 Fix event notification operations
  include/pmix_common.h.in
  src/client/pmix_client.c
  src/event/pmix_event.h
  src/event/pmix_event_notification.c
  src/server/pmix_server_ops.c
  src/tool/pmix_tool.c
  src/util/error.c
  test/simple/simptest.c
Labels: bug

#838 Deal with EOPNOTSUPP returned from getsockopt()
  src/mca/ptl/tcp/ptl_tcp.c
  src/mca/ptl/usock/ptl_usock.c
Labels: bug

#837 Deal with EOPNOTSUPP returned from getsockopt()
  src/mca/ptl/tcp/ptl_tcp.c
  src/mca/ptl/usock/ptl_usock.c
Labels: bug

#843 Convert the code base to use pmix_strncpy
  bindings/python/construct.py
  include/pmix_common.h.in
  include/pmix_extend.h
  src/client/pmi1.c
  src/client/pmi2.c
  src/client/pmix_client.c
  src/client/pmix_client_fence.c
  src/client/pmix_client_get.c
  src/client/pmix_client_pub.c
  src/client/pmix_client_spawn.c
  src/common/pmix_data.c
  src/common/pmix_iof.h
  src/event/pmix_event.h
  src/event/pmix_event_notification.c
  src/event/pmix_event_registration.c
  src/mca/base/pmix_mca_base_component_repository.c
  src/mca/bfrops/base/bfrop_base_copy.c
  src/mca/bfrops/base/bfrop_base_unpack.c
  src/mca/bfrops/v12/copy.c
  src/mca/bfrops/v12/unpack.c
  src/mca/bfrops/v20/copy.c
  src/mca/bfrops/v20/unpack.c
  src/mca/common/dstore/dstore_base.c
  src/mca/pif/bsdx_ipv4/pif_bsdx.c
  src/mca/pif/bsdx_ipv6/pif_bsdx_ipv6.c
  src/mca/pif/linux_ipv6/pif_linux_ipv6.c
  src/mca/pif/posix_ipv4/pif_posix.c
  src/mca/pif/solaris_ipv6/pif_solaris_ipv6.c
  src/mca/pnet/tcp/pnet_tcp.c
  src/mca/pnet/test/pnet_test.c
  src/mca/preg/native/preg_native.c
  src/mca/psensor/file/psensor_file.c
  src/mca/psensor/heartbeat/psensor_heartbeat.c
  src/mca/pshmem/mmap/pshmem_mmap.c
  src/mca/ptl/tcp/ptl_tcp.c
  src/mca/ptl/tcp/ptl_tcp_component.c
  src/mca/ptl/usock/ptl_usock_component.c
  src/server/pmix_server.c
  src/server/pmix_server_get.c
  src/server/pmix_server_ops.c
  src/tool/pmix_tool.c
  src/tools/plookup/plookup.c
  src/util/argv.c
  src/util/basename.c
  src/util/hash.c
  src/util/keyval_parse.c
  src/util/output.c
  src/util/pif.c
Labels: WIP-DNM

#846 Sync to formal PMIx v2 Standard doc
  include/pmix.h
  include/pmix_common.h.in
  include/pmix_server.h
  src/client/pmix_client.c
  src/common/pmix_data.c
  src/event/pmix_event_registration.c
  src/include/pmix_globals.c
  src/include/pmix_globals.h
  src/mca/gds/ds12/gds_dstore.c
  src/mca/gds/gds.h
  src/mca/gds/hash/gds_hash.c
  src/mca/pnet/base/base.h
  src/mca/pnet/base/pnet_base_fns.c
  src/mca/pnet/opa/pnet_opa.c
  src/mca/pnet/pnet.h
  src/mca/pnet/tcp/pnet_tcp.c
  src/mca/pnet/test/pnet_test.c
  src/mca/ptl/tcp/ptl_tcp.c
  src/mca/ptl/tcp/ptl_tcp_component.c
  src/mca/ptl/usock/ptl_usock.c
  src/mca/ptl/usock/ptl_usock_component.c
  src/runtime/pmix_init.c
  src/server/pmix_server.c
  src/server/pmix_server_get.c
  src/server/pmix_server_ops.c
  src/server/pmix_server_ops.h
  src/tool/pmix_tool.c
Labels: enhancement

#855 Bring the APIs into compliance with std
  src/client/pmix_client.c
  src/client/pmix_client_get.c
  src/client/pmix_client_spawn.c
  src/server/pmix_server.c
Labels: code-cleanup

#854 Bring the APIs into compliance with std
  include/pmix_common.h.in
  src/client/pmix_client.c
  src/client/pmix_client_get.c
  src/client/pmix_client_spawn.c
  src/server/pmix_server.c
Labels: code-cleanup
