Repository openpmix/openpmix, pull requests merged in 2018-02, with the labels that each got.

#670 preg: fixed object destructor: free(): invalid pointer
  src/mca/preg/native/preg_native.c
Labels: bug

#671 preg: fixed object destructor: free(): invalid pointer
  src/mca/preg/native/preg_native.c
Labels: blocker, bug

#673 ptl/base: Fix preliminary peer->info release
  src/mca/ptl/base/ptl_base_sendrecv.c
Labels: Target: 2.x, blocker, bug

#674 ptl/base: Fix preliminary peer->info release
  src/mca/ptl/base/ptl_base_sendrecv.c
Labels: Target: 2.x, blocker, bug

#677 Final updates in preparation for release
  NEWS
  VERSION
  src/mca/ptl/base/ptl_base_frame.c
Labels: bug, code-cleanup

#675 Update in preparation for v2.1.1 release
  NEWS
  VERSION
  config/pmix_check_attributes.m4
  contrib/pmix_jenkins.sh
  examples/pmi1client.c
  include/pmix_common.h.in
  src/client/pmix_client_pub.c
  src/include/pmix_globals.h
  src/mca/base/pmix_mca_base_var_group.c
  src/mca/gds/ds12/gds_dstore.c
  src/server/pmix_server.c
  src/server/pmix_server_get.c
  src/tool/pmix_tool.c
  test/cli_stages.c
  test/cli_stages.h
  test/simple/test_pmix.c
Labels: Target: 2.x, blocker, bug

#683 Correct an extern statement
  test/server_callbacks.c
Labels: Target: 2.x, Target: 3.x
