Repository openpmix/openpmix, pull requests merged in 2018-05, with the labels that each got.

#723 Fix deadlock in PMIx_Server_init in the error case
  src/server/pmix_server.c
Labels: Target: 2.x, Target: 3.x, bug

#727 Fix typo: PMIX_ERR_OPERATION_IN_PROGRESS -> PMIX_OPERATION_IN_PROGRESS
  src/mca/pnet/base/pnet_base_fns.c
  src/mca/pnet/pnet.h
Labels: blocker, bug

#728 Plug misc memory leaks on finalize
  include/pmix_common.h.in
  src/client/pmix_client.c
  src/event/pmix_event_registration.c
  src/include/pmix_globals.c
  src/mca/bfrops/base/bfrop_base_frame.c
  src/mca/gds/ds12/gds_dstore.c
  src/mca/gds/hash/gds_hash.c
  src/mca/ptl/tcp/ptl_tcp_component.c
  src/runtime/pmix_finalize.c
  src/util/hash.c
Labels: enhancement

#724 v2.1: Fix deadlock in PMIx_Server_init in the error case
  src/server/pmix_server.c
Labels: bug
