Repository openpmix/openpmix, pull requests merged in 2018-06, with the labels that each got.

#733 Fixed use of uninitialized value
  src/server/pmix_server_ops.c
Labels: Target: 2.x, bug

#736 v2.1: Fixed use of uninitialized value
  src/server/pmix_server_ops.c
Labels: bug

#744 Protect opa component when no hwloc available
  src/mca/pnet/opa/pnet_opa.c
Labels: Target: 3.x

#748 Plug misc memory leaks
  include/pmix_common.h.in
  src/mca/gds/hash/gds_hash.c
  test/simple/stability.c
Labels: enhancement

#768 Fix CC detection
  config/pmix_setup_cc.m4
  configure.ac
Labels: bug

#760 Bring branch up-to-date
  Makefile.am
  bindings/Makefile.am
  bindings/README
  bindings/python/Makefile.am
  bindings/python/README
  bindings/python/client.py
  bindings/python/cpmix.pxd
  bindings/python/pmix.pyx
  bindings/python/server.py
  bindings/python/setup.py
  config/pmix.m4
  config/pmix_check_cython.py
  config/pmix_setup_cc.m4
  configure.ac
  src/atomics/sys/architecture.h
  src/atomics/sys/arm/atomic.h
  src/atomics/sys/arm64/atomic.h
  src/atomics/sys/atomic.h
  src/atomics/sys/atomic_impl.h
  src/atomics/sys/cma.h
  src/atomics/sys/gcc_builtin/atomic.h
  src/atomics/sys/ia32/atomic.h
  src/atomics/sys/powerpc/atomic.h
  src/atomics/sys/sparcv9/atomic.h
  src/atomics/sys/sync_builtin/atomic.h
  src/atomics/sys/timer.h
  src/atomics/sys/x86_64/atomic.h
  src/atomics/sys/x86_64/timer.h
  src/atomics/sys/x86_64/update.sh
  src/class/pmix_object.h
  src/client/pmix_client.c
  src/event/pmix_event_notification.c
  src/hwloc/hwloc.c
  src/mca/plog/base/plog_base_stubs.c
  src/mca/pnet/base/pnet_base_frame.c
  src/mca/pnet/opa/configure.m4
  src/mca/pnet/opa/pnet_opa.c
  src/mca/pnet/opa/pnet_opa.h
  src/mca/pnet/tcp/pnet_tcp.c
  src/mca/psec/native/psec_native.c
  src/mca/ptl/tcp/ptl_tcp.c
  src/runtime/pmix_init.c
  src/server/pmix_server.c
  src/server/pmix_server_get.c
  src/threads/mutex.c
  src/threads/mutex_unix.h
  src/threads/thread_usage.h
  src/threads/wait_sync.h
  src/tool/pmix_tool.c
  test/simple/gwtest.c
Labels: bug, enhancement

#763 Updates to release state
  config/pmix_setup_cc.m4
  include/pmix_common.h.in
  src/atomics/sys/architecture.h
  src/atomics/sys/arm/atomic.h
  src/atomics/sys/arm64/atomic.h
  src/atomics/sys/atomic.h
  src/atomics/sys/atomic_impl.h
  src/atomics/sys/cma.h
  src/atomics/sys/gcc_builtin/atomic.h
  src/atomics/sys/ia32/atomic.h
  src/atomics/sys/powerpc/atomic.h
  src/atomics/sys/sparcv9/atomic.h
  src/atomics/sys/sync_builtin/atomic.h
  src/atomics/sys/timer.h
  src/atomics/sys/x86_64/atomic.h
  src/atomics/sys/x86_64/timer.h
  src/atomics/sys/x86_64/update.sh
  src/class/pmix_object.h
  src/client/pmix_client.c
  src/common/pmix_data.c
  src/event/pmix_event.h
  src/event/pmix_event_notification.c
  src/include/pmix_globals.h
  src/mca/ptl/ptl_types.h
  src/mca/ptl/tcp/ptl_tcp.c
  src/mca/ptl/tcp/ptl_tcp_component.c
  src/mca/ptl/usock/ptl_usock_component.c
  src/runtime/pmix_init.c
  src/server/pmix_server_ops.c
  src/threads/mutex.c
  src/threads/mutex_unix.h
  src/threads/thread_usage.h
  src/threads/wait_sync.h
  src/tool/pmix_tool.c
Labels: Target: 2.x, bug

#766 Add the stability test for ease of use
  .gitignore
  test/simple/Makefile.am
  test/simple/quietclient.c
  test/simple/simptest.h
  test/simple/stability.c
Labels: code-cleanup

#775 bindings/python: fix make install when VPATH is in use
  bindings/python/Makefile.am
Labels: bug

#777 dstore: fixed the logic of unmaping dstore segments
  src/mca/gds/ds12/gds_dstore.c
Labels: Target: 2.x, Target: 3.x, bug

#781 dstor: added the check of the dstore tracker is existed
  src/mca/gds/ds12/gds_dstore.c
Labels: bug

#778 v3.0 dstore: fixed the logic of unmaping dstore segments
  src/mca/gds/ds12/gds_dstore.c
Labels: bug

#779 v2.1 dstore: fixed the logic of unmaping dstore segments
  src/mca/gds/ds12/gds_dstore.c
Labels: bug

#780 v2.0 dstore: fixed the logic of unmaping dstore segments
  src/dstore/pmix_esh.c
Labels: bug
