Repository openpmix/openpmix, pull requests merged in 2019-02, with the labels that each got.

#1091 Require that the thread_usage macros always be inlined
  src/threads/thread_usage.h
Labels: Target: 2.x, Target: 3.x, bug

#1093 Update the job_ctrl return code
  src/server/pmix_server_ops.c
Labels: Target: 3.x, bug

#1102 Update configure logic
  config/pmix_setup_hwloc.m4
  config/pmix_setup_libevent.m4
Labels: Target: 2.x, Target: 3.x, Target: 4.x, bug

#1103 configury: automatically generate PMIX_NUMERIC_VERSION
  config/pmix.m4
  include/pmix_version.h.in
Labels: enhancement

#1105 Update configure logic
  config/pmix_setup_hwloc.m4
  config/pmix_setup_libevent.m4
Labels: bug

#1104 Update configure logic
  config/pmix_setup_libevent.m4
Labels: bug

#1110 configury: fix PMIX_NUMERIC_VERSION
  config/pmix.m4
Labels: bug

#1113 configury: fix PMIX_NUMERIC_VERSION
  config/pmix.m4
Labels: Target: 2.x, bug

#1112 configury: fix PMIX_NUMERIC_VERSION
  config/pmix.m4
Labels: Target: 3.x, bug

#1111 configury: fix PMIX_NUMERIC_VERSION
  config/pmix.m4
Labels: Target: 3.x, bug

#1116 Improve performance and hardness of pmix_strncpy
  include/pmix_common.h.in
Labels: Target: 2.x, Target: 3.x, Target: 4.x, code-cleanup

#1131 test/simple/simpclient: fix a type issue in model_registration_callba…
  test/simple/simpclient.c
Labels: bug

#1132 test/test_server: do not invoke libevent directly
  test/test_server.c
Labels: bug
