Repository openpmix/openpmix, pull requests merged in 2019-08, with the labels that each got.

#1389 configury: plug misc memory leaks
  config/c_get_alignment.m4
  config/pmix_check_compiler_version.m4
  config/pmix_check_icc.m4
Labels: enhancement, memory leak

#1382 dstore: fixed truncate key-names while restoring
  src/mca/common/dstore/dstore_base.c
Labels: bug

#1398 travis: test python bindings
  .travis.yml
Labels: enhancement

#1413 Remove unnecessary error log
  src/client/pmix_client_get.c
Labels: Target: 3.x, code-cleanup
