Repository openpmix/openpmix, pull requests merged in 2019-05, with the labels that each got.

#1222 Fix case of multiple launcher calls in job script
  src/include/pmix_globals.h
  src/mca/psec/native/psec_native.c
  src/mca/ptl/tcp/ptl_tcp_component.c
  src/tool/pmix_tool.c
Labels: bug

#1245 Fix atomic and error code paths
  src/server/pmix_server_ops.c
Labels: Target: 3.x, bug

#1246 server: Fix PMIx_Server_Finalize hang
  src/runtime/pmix_progress_threads.c
Labels: Target: 2.x, Target: 3.x, Target: 4.x, bug

#1237 Avoid double-free of tracker
  src/server/pmix_server_ops.c
Labels: blocker, bug

#1250 v3.1/server: Fix PMIx_Server_Finalize hang
  src/runtime/pmix_progress_threads.c
Labels: bug

#1251 v2.2/server: Fix PMIx_Server_Finalize hang
  src/runtime/pmix_progress_threads.c
Labels: bug

#1248 v2.0/server: Fix PMIx_Server_Finalize hang
  src/runtime/pmix_progress_threads.c
Labels: bug

#1249 v2.1/server: Fix PMIx_Server_Finalize hang
  src/runtime/pmix_progress_threads.c
Labels: bug

#1252 v3.0/server: Fix PMIx_Server_Finalize hang
  src/runtime/pmix_progress_threads.c
Labels: bug

#1260 Fix/test crosver
  src/include/types.h
  src/mca/ptl/base/ptl_base_sendrecv.c
  src/mca/ptl/ptl_types.h
  src/mca/ptl/usock/ptl_usock.c
Labels: WIP-DNM

#1263 ptl: Fix message header `nbytes` field ambiguity
  src/mca/ptl/ptl_types.h
Labels: Target: 2.x, Target: 3.x, Target: 4.x, bug, enhancement

#1271 PTL/usock: `usock` doesn't support Tools, fail query for this case.
  src/mca/ptl/usock/ptl_usock_component.c
Labels: bug

#1272 PTL/usock: `usock` doesn't support Tools, fail query for this case.
  src/mca/ptl/usock/ptl_usock_component.c
Labels: bug

#1264 PTL: Fix the connection establishment protocol (minimalistic)
  src/mca/psec/psec.h
  src/mca/ptl/tcp/ptl_tcp.c
  src/mca/ptl/tcp/ptl_tcp_component.c
  src/mca/ptl/usock/ptl_usock_component.c
Labels: Target: 3.x, Target: 4.x, blocker, bug

#1280 Fix/v3.1/cli connect v2
  src/mca/psec/psec.h
  src/mca/ptl/tcp/ptl_tcp.c
  src/mca/ptl/tcp/ptl_tcp_component.c
  src/mca/ptl/usock/ptl_usock_component.c
Labels: blocker, bug

#1281 Fix/v3.0/cli connect v2
  src/mca/psec/psec.h
  src/mca/ptl/tcp/ptl_tcp.c
  src/mca/ptl/tcp/ptl_tcp_component.c
  src/mca/ptl/usock/ptl_usock_component.c
Labels: blocker, bug

#1283 Fix/v2.1/cli connect v2
  src/mca/psec/psec.h
  src/mca/ptl/tcp/ptl_tcp.c
  src/mca/ptl/tcp/ptl_tcp_component.c
  src/mca/ptl/usock/ptl_usock_component.c
Labels: blocker, bug

#1282 Fix/v2.2/cli connect v2
  src/mca/psec/psec.h
  src/mca/ptl/tcp/ptl_tcp.c
  src/mca/ptl/tcp/ptl_tcp_component.c
  src/mca/ptl/usock/ptl_usock_component.c
Labels: blocker, bug
