Repository openpmix/openpmix, pull requests merged in 2019-07, with the labels that each got.

#1353 util/environ: use setenv() if available
  config/pmix.m4
  src/util/pmix_environ.c
Labels: enhancement

#1354 plug a misc memory leak in the pmix_query_caddy_t destructor
  src/include/pmix_globals.c
Labels: memory leak

#1363 Plug misc memory leaks
  src/client/pmix_client_get.c
  src/runtime/pmix_finalize.c
Labels: memory leak

#1359 Updates in prep for v3.1.4 release
  NEWS
  VERSION
  config/pmix.m4
  configure.ac
  src/client/pmix_client_get.c
  src/common/pmix_query.c
  src/include/pmix_globals.c
  src/include/pmix_globals.h
  src/mca/base/pmix_mca_base_component_find.c
  src/mca/base/pmix_mca_base_open.c
  src/mca/bfrops/v20/copy.c
  src/mca/gds/hash/gds_hash.c
  src/mca/pif/linux_ipv6/pif_linux_ipv6.c
  src/mca/pnet/opa/pnet_opa.c
  src/mca/pnet/tcp/pnet_tcp.c
  src/mca/ptl/tcp/ptl_tcp.c
  src/mca/ptl/tcp/ptl_tcp_component.c
  src/runtime/pmix_finalize.c
  src/runtime/pmix_init.c
  src/server/pmix_server_ops.c
  src/tool/pmix_tool.c
  src/util/compress.c
  src/util/output.c
  src/util/pmix_environ.c
  test/cli_stages.c
  test/simple/simptest.c
  test/test_common.h
  test/test_error.c
  test/test_server.c
Labels: bug, code-cleanup, enhancement

#1367 Don't whack the rendezvous file if you are a tool
  src/mca/ptl/tcp/ptl_tcp_component.c
Labels: Target: 3.x, bug

#1368 Backport support for libev
  .gitignore
  config/pmix.m4
  config/pmix_setup_libev.m4
  config/pmix_setup_libevent.m4
  src/client/pmix_client.c
  src/include/pmix_globals.c
  src/include/types.h
  src/mca/common/dstore/dstore_segment.c
  src/mca/ptl/tcp/ptl_tcp.c
  src/mca/ptl/usock/ptl_usock.c
  src/runtime/pmix_init.c
  src/runtime/pmix_progress_threads.c
  src/server/pmix_server.c
  src/tool/pmix_tool.c
  test/cli_stages.c
  test/cli_stages.h
  test/simple/gwtest.c
  test/simple/simptest.c
  test/simple/stability.c
  test/test_server.c
Labels: enhancement

#1193 Resolve get of proc-specific job-level info from another nspace
  examples/client.c
  examples/dynamic.c
  src/server/pmix_server.c
  src/server/pmix_server_get.c
Labels: Target: 3.x, bug, enhancement

#1379 Change IF_NAMESIZE to PMIX_IF_NAMESIZE
  src/mca/pif/bsdx_ipv4/pif_bsdx.c
  src/mca/pif/bsdx_ipv6/pif_bsdx_ipv6.c
  src/mca/pif/linux_ipv6/pif_linux_ipv6.c
  src/mca/pif/pif.h
  src/mca/pif/solaris_ipv6/pif_solaris_ipv6.c
  src/mca/ptl/tcp/ptl_tcp_component.c
  src/util/pif.h
Labels: Target: 3.x
