Repository openpmix/openpmix, pull requests merged in 2019-03, with the labels that each got.

#1125 modex: optimization of rank identification size reduction
  src/include/pmix_globals.c
  src/include/pmix_globals.h
  src/mca/common/dstore/dstore_base.c
  src/mca/common/dstore/dstore_common.h
  src/mca/gds/base/base.h
  src/mca/gds/base/gds_base_fns.c
  src/mca/gds/ds12/gds_ds12_base.c
  src/mca/gds/ds21/gds_ds21_base.c
  src/mca/gds/gds.h
  src/mca/gds/hash/gds_hash.c
  src/server/pmix_server.c
  src/server/pmix_server_ops.c
Labels: enhancement

#1144 bfrops: redefinition regtypes for internal usage
  include/pmix_common.h.in
  src/mca/bfrops/base/base.h
  src/mca/bfrops/base/bfrop_base_fns.c
  src/mca/bfrops/base/bfrop_base_pack.c
  src/mca/bfrops/base/bfrop_base_unpack.c
  src/mca/bfrops/v12/bfrop_v12.c
  src/mca/bfrops/v12/internal.h
  src/mca/bfrops/v12/pack.c
  src/mca/bfrops/v12/unpack.c
  src/mca/bfrops/v20/bfrop_pmix20.c
  src/mca/bfrops/v20/internal.h
  src/mca/bfrops/v20/pack.c
  src/mca/bfrops/v20/unpack.c
  src/mca/bfrops/v21/bfrop_pmix21.c
  src/mca/bfrops/v3/bfrop_pmix3.c
  src/mca/ptl/tcp/ptl_tcp.c
  src/mca/ptl/tcp/ptl_tcp_component.c
Labels: enhancement

#1154 Backport https://github.com/open-mpi/ompi/pull/6500
  src/atomics/sys/atomic_impl.h
Labels: bug

#1155 bfrops/base: silence a warning in PMIX_BFROP_UNPACK_SIZE_MISMATCH_FOU…
  src/mca/bfrops/base/base.h
Labels: code-cleanup

#1156 gds/ds21: update the pointer of `seg_hdr` when segment re-attached
  src/mca/gds/ds21/gds_ds21_lock_pthread.c
Labels: bug

#1161 bfrops/base: fix a typo in pmix_bfrops_base_unpack_app()
  src/mca/bfrops/base/bfrop_base_unpack.c
Labels: bug

#1159 v3.1/gds/ds21: update the pointer of `seg_hdr` when segment re-attached
  src/mca/gds/ds21/gds_ds21_lock_pthread.c
Labels: bug

#1164 Update header files
  NEWS
  VERSION
Labels: code-cleanup

#1163 Atomics: fix a compiler warning on POWER arch
  src/atomics/sys/powerpc/atomic.h
Labels: bug

#1152 Flexible integer packing with `psquash` framework in `bfrops` v4
  src/mca/bfrops/base/bfrop_base_pack.c
  src/mca/bfrops/v4/bfrop_pmix4.c
  src/mca/psquash/Makefile.am
  src/mca/psquash/base/Makefile.include
  src/mca/psquash/base/base.h
  src/mca/psquash/base/psquash_base_frame.c
  src/mca/psquash/base/psquash_base_select.c
  src/mca/psquash/flex128/Makefile.am
  src/mca/psquash/flex128/psquash_flex128.c
  src/mca/psquash/flex128/psquash_flex128.h
  src/mca/psquash/flex128/psquash_flex128_component.c
  src/mca/psquash/native/Makefile.am
  src/mca/psquash/native/psquash_native.c
  src/mca/psquash/native/psquash_native.h
  src/mca/psquash/native/psquash_native_component.c
  src/mca/psquash/psquash.h
Labels: enhancement

#1160 v2.2/gds/ds21: update the pointer of `seg_hdr` when segment re-attached
  src/mca/gds/ds21/gds_ds21_lock_pthread.c
Labels: bug

#1167 server: plug a memory leak in _collect_data()
  src/server/pmix_server_ops.c
Labels: code-cleanup

#1162 Avoid segfault in event notification
  src/event/pmix_event_notification.c
  src/include/pmix_globals.h
  src/mca/ptl/base/ptl_base_sendrecv.c
  src/server/pmix_server.c
  src/server/pmix_server_ops.c
Labels: bug

#1171 psquash/flex128: Fix mismatch prototype
  src/mca/psquash/flex128/psquash_flex128.c
Labels: bug

#1135 modex: avoid exchange unnecessary buffer when collect flag is not set
  src/mca/bfrops/bfrops_types.h
  src/mca/gds/base/gds_base_fns.c
  src/server/pmix_server.c
  src/server/pmix_server_ops.c
Labels: enhancement

#1182 configury: fix git source tree is detected
  config/distscript.sh
  config/pmix.m4
Labels: enhancement

#1180 Configure logic updates
  NEWS
  config/distscript.sh
  config/pmix.m4
  config/pmix_config_pthreads.m4
  config/pmix_config_threads.m4
Labels: bug
