Repository openpmix/openpmix, pull requests merged in 2019-01, with the labels that each got.

#1029 epilog: fix a typo in pmix_execute_epilog()
  src/include/pmix_globals.c
Labels: bug

#1028 pmix_control: plug a memory leak in query_cbfunc()
  src/common/pmix_control.c
Labels: enhancement

#1036 gds/ds21: fix support for 32 bits arch
  src/mca/gds/ds21/gds_ds21_file.c
Labels: bug

#1031 common/dstore: plug a memory leak in pmix_common_dstor_finalize()
  src/mca/common/dstore/dstore_base.c
Labels: enhancement

#1050 Fixes PMIx_generate_regex ordering
  src/mca/preg/base/preg_base_frame.c
  src/mca/preg/native/preg_native.c
  src/mca/preg/preg_types.h
Labels: bug

#1056 Use affected procs for filtering notifications
  include/pmix_common.h.in
  src/client/pmix_client_spawn.c
  src/common/pmix_query.c
  src/event/pmix_event_notification.c
  src/event/pmix_event_registration.c
  src/mca/pnet/base/pnet_base_fns.c
  src/server/pmix_server_ops.c
  src/server/pmix_server_ops.h
Labels: Target: 3.x, Target: 4.x, bug

#1059 configury: enhance C11 detection
  config/pmix_setup_cc.m4
Labels: enhancement

#1060 test/simple/simptest: do not PMIX_THREADSHIFT() an object allocated o…
  test/simple/simptest.c
Labels: bug

#1063 Save hostname for use in responding to queries
  examples/tool.c
  src/common/pmix_query.c
  src/include/pmix_globals.h
  src/mca/ptl/tcp/ptl_tcp_component.c
  src/runtime/pmix_init.c
  src/server/pmix_server_ops.c
Labels: Target: 2.x, Target: 3.x, enhancement

#1083 Shift the non-standard macros to pmix_extend.h
  include/pmix_extend.h
  test/test_common.h
Labels: code-cleanup

#1084 test: multiserver fixes
  test/test_server.c
  test/test_server.h
Labels: bug

#1088 Update docs for release
  HACKING
  INSTALL
  LICENSE
  NEWS
  VERSION
Labels: documentation

#1087 Update all doc files for release
  HACKING
  INSTALL
  LICENSE
  NEWS
  README
  VERSION
Labels: documentation
