Repository openpmix/openpmix, pull requests merged in 2020-12, with the labels that each got.

#1933 Remove stale config command
  config/pmix.m4
Labels: code-cleanup

#1942 Update NEWS and VERSION for rc
  NEWS
  VERSION
Labels: documentation

#1944 Adjust Python bindings to match C
  bindings/python/pmix.pyx
Labels: Target: 4.x

#1966 Fix typo in checking cached events
  src/event/pmix_event_registration.c
Labels: Target: 3.x, Target: 4.x

#1971 Complete revision of Python bindings
  bindings/python/pmix.pxi
  bindings/python/pmix.pyx
  include/pmix_common.h.in
  src/mca/gds/hash/gds_hash.c
  test/pmix_client.c
  test/python/sched.py
  test/python/server.py
Labels: Target: 4.x
