Repository openpmix/openpmix, pull requests merged in 2021-01, with the labels that each got.

#2002 Add the PMIx Standard version level to the version string
  .github/actions/mlnx/entrypoint.sh
  VERSION
  config/pmix.m4
  config/pmix_get_version.sh
  config/pmix_summary.m4
  src/client/pmix_client.c
Labels: enhancement

#2005 Disable IPv6 by default
  src/mca/ptl/base/ptl_base_frame.c
  src/mca/ptl/base/ptl_base_listener.c
Labels: Target: 4.x

#2013 v4: Add the PMIx Standard version level to the version string
  .github/actions/mlnx/entrypoint.sh
  VERSION
  config/pmix.m4
  config/pmix_get_version.sh
  config/pmix_summary.m4
  src/client/pmix_client.c
Labels: enhancement

#2041 Various HWLOC support changes plus one OFI config fix
  config/pmix_check_ofi.m4
  src/mca/ploc/hwloc/ploc_hwloc.c
  src/server/pmix_server.c
  src/server/pmix_server_ops.h
  test/simple/simptest.c
Labels: PMIx Standard (to be filed)
